source "https://rubygems.org"

gem 'rake', '>= 12.3.3'

# MySQL, PostgreSQL
gem 'activerecord', '>= 6.1.7.1'
gem 'activerecord-mysql2-adapter'
gem 'iconv'
gem 'pg'

# MongoDB
gem 'mongo', '>= 2.0.0'
gem 'bson_ext', '>= 1.12.0'

# Redis
gem 'redis'

# Riak
gem 'riak-client'
